<?php

declare(strict_types=1);

namespace Modules\Core\Models;

use Illuminate\Database\Eloquent\Factories\Factory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Support\Carbon;
use Modules\Core\Database\Factories\TermWeekFactory;
use Modules\Core\Domain\Concerns\BelongsToSchool;

/**
 * Book A CORE-03 §2 — generated by `ACT-GenerateTermWeeks`, excluding
 * holidays and half-term.
 *
 * @property int $id
 * @property int $school_id
 * @property int $term_id
 * @property int $week_number
 * @property Carbon $starts_on
 * @property Carbon $ends_on
 * @property bool $is_teaching_week
 * @property string|null $label
 * @property Carbon|null $created_at
 * @property Carbon|null $updated_at
 * @property-read Term $term
 */
class TermWeek extends Model
{
    use BelongsToSchool;

    /** @use HasFactory<TermWeekFactory> */
    use HasFactory;

    protected $fillable = [
        'school_id',
        'term_id',
        'week_number',
        'starts_on',
        'ends_on',
        'is_teaching_week',
        'label',
    ];

    protected function casts(): array
    {
        return [
            'starts_on' => 'date',
            'ends_on' => 'date',
            'is_teaching_week' => 'boolean',
        ];
    }

    /**
     * @return Factory<self>
     */
    protected static function newFactory(): Factory
    {
        return TermWeekFactory::new();
    }

    /**
     * @return BelongsTo<Term, $this>
     */
    public function term(): BelongsTo
    {
        return $this->belongsTo(Term::class);
    }
}
